### ISSUE TITLE
The new build of `libslang.dll` no longer renders the chars in Code Page 850 with SLsmg_write_char()

### ISSUE THREAD

**Issue by eddebaby** [dkfans/ADiKtEd#6]
Moved from https://github.com/dkfans/ADiKtEd/pull/4#issuecomment-701922215:
The new build of `libslang.dll` has a graphical glitch where the box border is not drawn with chars from ~~Code Page 437~~ Code Page 850 anymore, so it does not look like a border at all. 

map.exe actually uses **Code Page 850** not **Code Page 437** as I previously thought, they are very similar (850 is based on 437), and the char codes for the lines/borders are the same.

I'm not sure of the precise details, but presumably it is using the build environment's default codepage instead.

With currently buildable `libslang.dll` (incorrect):
![image](https://user-images.githubusercontent.com/1984342/94759659-65a29c00-0398-11eb-81b6-9eded09f5bc0.png)
With 0.95's built `libslang.dll` (correct):
![image](https://user-images.githubusercontent.com/1984342/94759600-3e4bcf00-0398-11eb-845d-0eb4a3496497.png)

[Extended ASCII characters - Code Page 437](https://en.wikipedia.org/wiki/Code_page_437). 

These are the border chars from ~~Code Page 437~~ Code Page 850: [here](https://github.com/dkfans/ADiKtEd/blob/f55a4313835ede1be0239a0283eda1d42cf1861b/mapslang/output_scr.c#L233) and [here](https://github.com/dkfans/ADiKtEd/blob/f55a4313835ede1be0239a0283eda1d42cf1861b/mapslang/output_scr.c#L252)

Maybe convert to Unicode [(Code Page 437 to Unicode)](https://en.wikipedia.org/w/index.php?title=Code_page_437&oldid=565442465#Characters) [(Code Page 850 to Unicode)](https://en.wikipedia.org/wiki/Code_page_850#Character_set) or [UTF-8](http://www.fileformat.info/info/charset/UTF-8/list.htm), and adjust some functions in mapslang e.g [here](https://github.com/dkfans/ADiKtEd/blob/461efdfae1d7640c19aaafdec140331aa3258fd5/mapslang/output_scr.c#L110) and/or [here](https://github.com/dkfans/ADiKtEd/blob/f55a4313835ede1be0239a0283eda1d42cf1861b/mapslang/output_scr.c#L246)?

I tried many ways external to mapslang, but had no luck. It might be best to rewrite mapslang code and look to the future.

Otherwise:

Converting codepages for gcc: [here](http://www.neoegm.com/tech/programming/c-cpp/how-to-compile-c-console-programs-which-support-special-characters-iso-8859-1/)

and other search terms:
code page
charset
SLsmg_write_char
SLsmg_set_char_set
SLutf8_enable
CP437
CP850
"S-lang"
slang
gcc
chcp
iconv
mingw32
MSYS2
437
850

**Comment by dotted** [comment]
Fixed in #29
